sonar.projectKey=aptlogica_go-postgres-rest
sonar.organization=aptlogica
sonar.language=go
sonar.sources=pkg
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/*_test.go,**/*_testdata/**
